apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1  # Puedes dejarlo en 1, el HPA manejará la escala
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nicolasortiz05/back-taller:1.1  # Verifica que la imagen esté en Docker Hub
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql-service:3306/mydb"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "root"

        # 💡 Agrega estos valores aquí para que el HPA pueda monitorear el uso de CPU
        resources:
          requests:
            cpu: "50m"   # El pod solicitará al menos 50 millicores
          limits:
            cpu: "250m"  # No podrá usar más de 250 millicores

        startupProbe:
          httpGet:
            path: /api/datos
            port: 8080
          initialDelaySeconds: 60 
          timeoutSeconds: 10        
          periodSeconds: 20       
          failureThreshold: 6      
