apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend  # Debe coincidir con el nombre del Deployment

  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75  # Kubernetes escalará si el uso de CPU supera el 75%

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60