apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi  # Espacio reservado
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage-retain
  hostPath:
    path: "/mnt/data/mysql"  # Ruta en el nodo donde se guardarán los datos
